spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        #show_sql: true #jpa가 실행하는 쿼리를 콘솔에 보여줌
        #dialect: org.hibernate.dialect.Oracle10gDialect

#  data:
#    web:
#      pageable:
#        default-page-size: 10 # 기본 페이지 사이즈
#        max-page-size: 2000 # 최대 페이지 사이즈
#        one-indexed-parameters: true # 페이지 0 -> 1부터 시작

logging:
  level:
    org.hibernate.SQL: debug #로그파일로 남김; show-sql 은 콘솔에만 노출
#    org.hibernate.type: trace
